Interface cache
fluencelabs/fluence pull request #1052
Opened 2021-03-10 13:41 UTC by DieMyst

2021-03-11 12:01 UTC, justprosh commented on crates/test-utils/src/utils.rs
> +use serde_json::Value as JValue;
I think you should group imports like this:
- local imports
- other things from fluence org (like fce, aquamarine imports)
- other imports

2021-03-11 12:21 UTC, justprosh commented on particle-modules/src/modules.rs
> +use serde_json::{json, Value as JValue, Value};
Maybe leave only one `Value`

2021-03-11 12:25 UTC, justprosh approved these changes

2021-03-11 12:25 UTC, justprosh commented on particle-node/tests/network_explore.rs
> +
redundant blank line

2021-03-15 14:39 UTC, folex requested changes

2021-03-15 14:39 UTC, folex commented on particle-modules/src/modules.rs
> +        let blueprints_cache: Blueprints = Arc::new(RwLock::new(bp_map));
no need to specify type here

2021-03-15 14:39 UTC, folex commented on particle-modules/src/modules.rs
> +        }
Maybe move that logic to `load_blueprints` function? Return HasMap right away

2021-03-15 14:39 UTC, folex commented on particle-modules/src/modules.rs
> +                    .ok_or(EmptyDependenciesList { id: id.to_string() })?;
Hm. I wonder if we check that dependencies aren't empty on `add_blueprint`. Maybe lets check?

2021-03-15 14:39 UTC, folex commented on particle-modules/src/modules.rs
> +    pub fn get_interface_by_blueprint_id(&self, id: &str) -> Result<JValue> {
```suggestion
    pub fn get_facade_interface(&self, blueprint_id: &str) -> Result<JValue> {
```

2021-03-15 14:39 UTC, folex commented on particle-modules/src/modules.rs
> +    fn get_interface_by_hash_internal(
you can move that function from the `impl` block. Then you can call it without `Self::`

2021-03-15 14:39 UTC, folex commented on particle-modules/src/modules.rs
> +                json
```suggestion
                let path = modules_dir.join(module_file_name(hash));
                let interface = module_interface(&path)
                    .map_err(|err| ReadModuleInterfaceError { path, err })?;
                let json = json!(interface);
                json
```

2021-03-15 14:39 UTC, folex commented on particle-modules/src/modules.rs
> +                })
You can do `json!`, and that likely wouldn't require cloning & avoid error handling

2021-03-15 14:39 UTC, folex commented on particle-modules/src/modules.rs
> +    }
Maybe add a test that list of modules gets cached after get_interface? I believe you can access cache field from tests.

2021-03-15 14:39 UTC, folex commented on particle-services/src/app_services.rs
> +    fn test_get_interface_cache() {
How does it test cache?

2021-03-15 14:39 UTC, folex commented on particle-services/src/app_services.rs
> +        let service_id2 = create_service(&pas, "tetra".to_string(), module.clone()).unwrap();
Maybe remove wasm module from filesystem to check that it is cached?

2021-03-15 14:39 UTC, folex commented on particle-modules/src/modules.rs
> +    blueprints: Blueprints,
Discussed in slack and decided to remove that alias for consistency

2021-03-16 08:49 UTC, folex requested changes

2021-03-16 08:49 UTC, folex commented on particle-modules/src/modules.rs
> +            if dependencies.is_empty() {
I think that should go before `resolve_hash` for performance reasons

2021-03-16 08:49 UTC, folex commented on particle-modules/src/modules.rs
> +fn get_interface_by_hash_internal(
let's drop `_internal`

2021-03-16 08:49 UTC, folex commented on particle-services/src/app_services.rs
> +
I think it is better to check that expected module was really removed. For example, check that it was there after upload, and then it is missing after remove_file

2021-03-16 09:56 UTC, folex approved these changes

2021-03-16 10:02 UTC, merged