remove_script: remove --force flag, auth with management key
fluencelabs/fluence pull request #1054
Opened 2021-03-15 09:24 UTC by justprosh

2021-03-15 16:57 UTC, DieMyst commented on particle-closures/src/host_closures.rs
> +        if params.init_user_id != self.management_peer_id {
you can add a test here to check that the logic is working

2021-03-16 08:20 UTC, folex requested changes

2021-03-16 08:20 UTC, folex commented on particle-closures/src/host_closures.rs
> +        if params.init_user_id != self.management_peer_id {
Wait, why deny? Anyone should be able to remove scripts they own. management_peer_id can remove scripts from anyone, that is.

2021-03-16 08:20 UTC, folex commented on particle-node/tests/script_storage.rs
> +        Some(swarms[0].keypair.clone()),
we need to check that owner of the script can remove the script

2021-03-16 08:24 UTC, folex commented on particle-node/tests/script_storage.rs
> +    let mut client = ConnectedClient::connect_to_with_peer_id(
let's rename to `connect_as_owner`

2021-03-16 08:24 UTC, folex commented on particle-node/tests/script_storage.rs
> +        Some(swarms[0].keypair.clone()),
let's rename `ConnectedSwarm::keypair` to `management_keypair`

2021-03-16 15:18 UTC, folex approved these changes

2021-03-16 15:18 UTC, folex commented on crates/test-utils/src/misc.rs
> +                management_keypair: keypair,
you can rename `keypair` to avoid `:`

2021-03-16 15:29 UTC, merged