set rust toolchain
fluencelabs/fluence pull request #1126
Opened 2021-06-14 07:17 UTC by dzmitry-lahoda

so other can easy build and switch to this repo

2021-06-14 07:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/fluencelabs/fluence?pullRequest=1126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/fluencelabs/fluence?pullRequest=1126) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/fluencelabs/fluence?pullRequest=1126) it.</sub>

2021-06-14 07:17 UTC, dzmitry-lahoda commented
i want to try out https://github.com/fluencelabs/fluence/pull/1110

2021-06-14 11:41 UTC, folex requested changes
Specific version in CI is needed because on nightly channel not all components are released at once. So if using just `nightly` (i.e. latest nightly), it's possible that `rustfmt` will be missing, for example, and build will fail.

This is inevitable for latest nightly, so we're using specific version only as a mean to avoid that problem.

2021-06-14 11:41 UTC, folex commented on rust-toolchain
> +nightly-2021-04-24
I'd put just `nightly` here

2021-06-14 11:41 UTC, folex commented on .github/workflows/rust_ci.yml
> +          # keep in sync rust-toolchain (you may cat into here as option)
```suggestion
```

2021-06-14 11:41 UTC, folex commented on rust-toolchain
> +nightly-2021-04-24
I wonder if it's possible to move `rust-toolchain` to `.rustc` or `.cargo` to avoid cluttering project root with files

2021-06-14 13:38 UTC, dzmitry-lahoda commented on rust-toolchain
> +nightly-2021-04-24
it will not work. the version must be exactly same as in ci

2021-06-14 13:40 UTC, dzmitry-lahoda commented on rust-toolchain
> +nightly-2021-04-24
for thoose who upgrades can use https://rust-lang.github.io/rustup/overrides.html - so the problem of version is the only problem of upgrader, not of others

2021-06-14 13:41 UTC, dzmitry-lahoda commented on rust-toolchain
> +nightly-2021-04-24
can use override per folder
per package

2021-06-14 13:41 UTC, dzmitry-lahoda commented on rust-toolchain
> +nightly-2021-04-24
i do not think so https://rust-lang.github.io/rustup/overrides.html

2021-06-14 13:42 UTC, folex commented on rust-toolchain
> +nightly-2021-04-24
> it will not work. the version must be exactly same as in ci for master

what wouldn't work?

2021-06-14 14:19 UTC, dzmitry-lahoda commented on rust-toolchain
> +nightly-2021-04-24
i have newer nightly that this, and it fails to compule dht (becayse of try feature v2). similar as i recall was for this repo. anyway - nightly must be either latest always, or if you do not update - must be precise release to allow other peoples collaborate on code.

2021-06-14 14:22 UTC, folex commented on rust-toolchain
> +nightly-2021-04-24
Ah, I see. Node doesn't compile on higher versions. That's a very unusual situation, I'll fix that ASAP

2021-06-14 15:14 UTC, folex commented on rust-toolchain
> +nightly-2021-04-24
I've fixed the problem with `try_feature` in #1127. Now you can safely use `nightly` in `rust-toolchain` file

2021-06-15 09:52 UTC, folex commented on rust-toolchain
> +nightly-2021-04-24
@dzmitry-lahoda, let's change to `nightly` and commit

2021-06-17 09:33 UTC, folex requested changes
In aqua-dht repo it turned out ([1](https://app.circleci.com/pipelines/github/fluencelabs/aqua-dht/148/workflows/72d608b3-9d6e-419d-92c4-91e8fb4940f6/jobs/228), [2](https://github.com/fluencelabs/aqua-dht/runs/2846799062)) that we also need to add
```
rustup override set nightly-2021-06-14-x86_64-unknown-linux-gnu
```

to override `rust-toolchain` file for CI

```

2021-06-17 10:29 UTC, dzmitry-lahoda commented
@folex are you sure you are not complicating things? may be make master same as CI? if somebody wants to use new feature, have a branch and wait for CI is ready.

2021-06-17 10:29 UTC, dzmitry-lahoda commented
Nightly already `alfa`, so you are trying to use alfa-alfa-unknown.

2021-06-17 10:31 UTC, folex commented
> @folex are you sure you are not complicating things? may be make master same as CI? if somebody wants to use new feature, have a branch and wait for CI is ready.

I'm thinking about developers who don't have installed `nightly-2021-06-14`, but have installed `nightly`. I see no major reason to force them to install `nightly-2021-06-14`.

If it not random unavailability of components in latest `nightly`, I'd use it in CI.

2021-06-17 11:15 UTC, dzmitry-lahoda commented
as a other developer i prefer to install exact version which works, and ci proves that. it like depending on exact p2p crate instead on random latest.

2021-06-17 11:50 UTC, folex commented
> as a other developer i prefer to install exact version which works, and ci proves that. it like depending on exact p2p crate instead on random latest.

I think you have a good point that I haven't thought about initially. Since we're using unstable features like `try_trait_v2`, build on `nightly` might brake, and confuse developers who try to build node from sources. 🤔

2021-06-17 12:07 UTC, dzmitry-lahoda commented
actually i did not wanted nodes, i wanted tool (rust client) - so I added new crate client to fluence fork.

2021-06-17 14:27 UTC, dzmitry-lahoda commented
so what should be done?

2021-06-18 10:07 UTC, folex approved these changes

2021-06-18 10:07 UTC, merged