Draft: Builtins for services metrics
fluencelabs/fluence pull request #1287
Opened 2022-06-30 10:47 UTC by kmd-fl

Corresponding aqua interface
```aqua
data Stat:
  req_count: u64
  deltas_bytes: []u64
  total_deltas_bytes: u64
  delta_avg_bytes: u64

data FunctionStat:
  name: string
  stat: Stat

data ServiceStat:
  stat: Stat
  function_stats: []FunctionStat

data StatResult:
  status: bool
  error: string
  result: ?ServiceStat

service Stat("stat"):
  service_stat(service_id: string) -> StatResult
```

2022-06-30 11:18 UTC, folex commented
I would divide `req_count` into `success_call_count` and `fail_call_count`

2022-07-07 14:00 UTC, justprosh commented on particle-builtins/src/builtins.rs
> +            .unwrap()
This unwrap looks not so good and `if` statement too. Maybe you should write smth like:
```
let metrics = self.services.metrics.as_ref()?;
...
if let Some(result) = 
```

2022-07-28 16:20 UTC, folex requested changes

2022-07-28 16:20 UTC, folex commented on particle-builtins/src/builtins.rs
> +        }))
Why this structure?

2022-07-28 16:20 UTC, folex commented on particle-node/tests/builtin.rs
> +        assert_eq!(result.get("status"), Some(&json!(true)));
Is it possible to also check that service stats actually appear there and are counted correctly?

2022-07-29 17:23 UTC, kmd-fl commented on crates/peer-metrics/src/services_metrics/builtin.rs
> +    /// Average number of observations
Well, it's not a _rolling_ average because it's not an average per some period, but since the node starts. It's literally `total / success_req_count`, so maybe we should do something with it later.

2022-07-29 17:25 UTC, kmd-fl commented on crates/peer-metrics/src/services_metrics/builtin.rs
> +    fn update(&mut self, value: f64, count: f64) {
Yeah, it's a bad interface, I did it just to avoid type casting. Changed it.

2022-07-29 17:27 UTC, kmd-fl commented on crates/peer-metrics/src/services_metrics/builtin.rs
> +        let mut content = self.content.write().unwrap();
I've read that it should be safe, is it not? I changed it though.

2022-07-29 17:27 UTC, kmd-fl commented on crates/peer-metrics/src/services_metrics/mod.rs
> +        f.debug_struct("ServicesMetrics").finish()
Yeah. `ParticleAppServices` implements `Debug`, so we need to add an implementation for `ServiceMetrics`, but I'm not sure that it's possible to implement something more sensible.

2022-07-29 17:49 UTC, kmd-fl commented on particle-node/tests/builtin.rs
> +        assert_eq!(result.get("status"), Some(&json!(true)));
Yeah, it is. Found that it's possible to parse stats from `JValue`, but I need more time to implement it properly.

2022-08-01 15:49 UTC, folex commented on particle-node/tests/builtin.rs
> +        assert_eq!(result.get("status"), Some(&json!(true)));
kk, I drafted a simple impl

2022-08-01 15:50 UTC, folex approved these changes

2022-08-01 16:02 UTC, merged